### ISSUE TITLE
Is this DbUnitTest Support Mybatis ?

### ISSUE THREAD

**Issue by watsonhaw5566** [camassia-io/spring-boot-test-dbunit#1]
Out Team use Mybaits plus and Koltin. I read the README.MD don't found mybatis caes .So wanna to ask support that ?
Thanks, I like this project.

**Comment by ed0906** [comment]
Hi, Sorry for the late reply. I'm not familiar with Mybatis, would that still be using Spring Boot?

**Comment by ed0906** [comment]
Having read through some docs, as long as you are using [mybatis-spring](https://mvnrepository.com/artifact/org.mybatis/mybatis-spring) this library should work fine

Just `@Autowire` in your repository / mapper class into your test in the place of JdbcTemplate in the examples

**Comment by watsonhaw5566** [comment]
> Having read through some docs, as long as you are using [mybatis-spring](https://mvnrepository.com/artifact/org.mybatis/mybatis-spring) this library should work fine
> 
> Just `@Autowire` in your repository / mapper class into your test in the place of JdbcTemplate in the examples

no problem, thanks friend.
